image: maven:3.8.1

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"

tasks:
  - name: Install dependencies
    command: mvn install

  - name: Run tests
    command: mvn test

  - name: Run TestRunner
    command: mvn exec:java -Dexec.mainClass="runner.TestRunner"
